announcements/urls.py
from unicodedata import name
from django.urls import path
from . import views


app_name = 'announcements'

urlpatterns = [
    path('', views.AnnouncementsListView.as_view(), name='all'),
    path('<int:pk>/detail', views.AnnouncementsDetailView.as_view(), name='announcements_detail'),
    path('create/', views.AnnouncementsCreateView.as_view(), name='announcements_create'),
    path('<int:pk>/update', views.AnnouncementsUpdateView.as_view(), name='announcements_update'),
    path('<int:pk>/delete', views.AnnouncementsDeleteView.as_view(), name='announcements_delete'),
    
]

assignments/urls.py
from unicodedata import name
from django.urls import path
from . import views


app_name = 'assignments'

urlpatterns = [
    path('', views.AssignmentsListView.as_view(), name='all'),
    path('<int:pk>/detail', views.AssignmentsDetailView.as_view(), name='assignments_detail'),
    path('create/', views.AssignmentsCreateView.as_view(), name='assignments_create'),
    path('<int:pk>/update', views.AssignmentsUpdateView.as_view(), name='assignments_update'),
    path('<int:pk>/delete', views.AssignmentsDeleteView.as_view(), name='assignments_delete'),
    
]

content/urls.py
from unicodedata import name
from django.urls import path
from . import views


app_name = 'content'

urlpatterns = [
    path('', views.ContentListView.as_view(), name='all'),
    path('content/<int:pk>/detail', views.ContentDetailView.as_view(), name='content_detail'),
    path('content/create/', views.ContentCreateView.as_view(), name='content_create'),
    path('content/<int:pk>/update', views.ContentUpdateView.as_view(), name='content_update'),
    path('content/<int:pk>/delete', views.ContentDeleteView.as_view(), name='content_delete'),
    
]

lms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('content.urls')),
    path('assignments/', include('assignments.urls')),
    path('quizes/', include('quizes.urls')),
    path('announcements/', include('announcements.urls')),

]

quizes/urls.py
from unicodedata import name
from django.urls import path
from . import views


app_name = 'quizes'

urlpatterns = [
    path('', views.QuizesListView.as_view(), name='all'),
    path('<int:pk>/detail', views.QuizesDetailView.as_view(), name='quizes_detail'),
    path('create/', views.QuizesCreateView.as_view(), name='quizes_create'),
    path('<int:pk>/update', views.QuizesUpdateView.as_view(), name='quizes_update'),
    path('<int:pk>/delete', views.QuizesDeleteView.as_view(), name='quizes_delete'),
    
]

announcements/models.py
from django.db import models


# Create your models here.
class Announcements(models.Model):
    title  =  models.CharField(max_length=200,)
    description  =  models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        return self.title

assignments/models.py
from django.db import models


# Create your models here.
class Assignments(models.Model):
    title  =  models.CharField(max_length=200,)
    description  =  models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        return self.title

content/models.py
from django.db import models

# Create your models here.
class Content(models.Model):
    title  =  models.CharField(max_length=200,)
    description  =  models.TextField(blank=True, null=True)
    year = models.PositiveIntegerField(blank=True, null=True)
    def __str__(self) -> str:
            if self.year:
                return f"{self.title} ({self.year})"

            return self.title

quizes/models.py
from django.db import models


# Create your models here.
class Quizes(models.Model):
    title  =  models.CharField(max_length=200,)
    description  =  models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        return self.title

announcements/views.py
from django.shortcuts import render

# Create your views here.
from audioop import reverse
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Announcements


class AnnouncementsBaseView(View):
    model = Announcements
    fields = '__all__'
    success_url = reverse_lazy('announcements:all')



class AnnouncementsListView(AnnouncementsBaseView, ListView):
     """ view to list all Announcementss, use the Announcements_
    list variable in the remplate to access all Announcements objects """
   
   
class AnnouncementsDetailView(AnnouncementsBaseView, DetailView):
    """ View to list details from one Announcements 
    use Announcements variable in template to acess specific Announcements here 
    and in the views bellow """

class AnnouncementsCreateView(AnnouncementsBaseView, CreateView):
    """ View to update Announcements """


   
class AnnouncementsUpdateView(AnnouncementsBaseView, UpdateView):
    """ View to update Announcements """


   
class AnnouncementsDeleteView(AnnouncementsBaseView, DeleteView):
    """View to delete a Announcements """

assignments/views.py
from django.shortcuts import render

# Create your views here.
from audioop import reverse
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Assignments


class AssignmentsBaseView(View):
    model = Assignments
    fields = '__all__'
    success_url = reverse_lazy('assignments:all')



class AssignmentsListView(AssignmentsBaseView, ListView):
     """ view to list all Assignmentss, use the Assignments_
    list variable in the remplate to access all Assignments objects """
   
   
class AssignmentsDetailView(AssignmentsBaseView, DetailView):
    """ View to list details from one Assignments 
    use Assignments variable in template to acess specific Assignments here 
    and in the views bellow """

class AssignmentsCreateView(AssignmentsBaseView, CreateView):
    """ View to update Assignments """


   
class AssignmentsUpdateView(AssignmentsBaseView, UpdateView):
    """ View to update Assignments """


   
class AssignmentsDeleteView(AssignmentsBaseView, DeleteView):
    """View to delete a Assignments """

content/views.py
from audioop import reverse
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Content


class ContentBaseView(View):
    model = Content
    fields = '__all__'
    success_url = reverse_lazy('content:all')



class ContentListView(ContentBaseView, ListView):
     """ view to list all Contents, use the Content_
    list variable in the remplate to access all Content objects """
   
   
class ContentDetailView(ContentBaseView, DetailView):
    """ View to list details from one Content 
    use Content variable in template to acess specific Content here 
    and in the views bellow """

class ContentCreateView(ContentBaseView, CreateView):
    """ View to update Content """


   
class ContentUpdateView(ContentBaseView, UpdateView):
    """ View to update Content """


   
class ContentDeleteView(ContentBaseView, DeleteView):
    """View to delete a Content """

quizes/views.py
from django.shortcuts import render

# Create your views here.
from audioop import reverse
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Quizes


class QuizesBaseView(View):
    model = Quizes
    fields = '__all__'
    success_url = reverse_lazy('quizes:all')



class QuizesListView(QuizesBaseView, ListView):
     """ view to list all Quizess, use the Quizes_
    list variable in the remplate to access all Quizes objects """
   
   
class QuizesDetailView(QuizesBaseView, DetailView):
    """ View to list details from one Quizes 
    use Quizes variable in template to acess specific Quizes here 
    and in the views bellow """

class QuizesCreateView(QuizesBaseView, CreateView):
    """ View to update Quizes """


   
class QuizesUpdateView(QuizesBaseView, UpdateView):
    """ View to update Quizes """


   
class QuizesDeleteView(QuizesBaseView, DeleteView):
    """View to delete a Quizes """

announcements/templates/announcements/announcements_confirm_delete.html
{% extends "base.html" %}

{% block content %}

{% url 'announcements:all' as list_all %}

<div class="container d-flex justify-content-center mt-5" style="width: 50%;">
    <div class="col mt-5 text-center">
        <h1 class="mb-5">Delete content</h1>

        <p class="h5">Are you sure you want to delete the content:</p>
        <h3 class="my-5">{{ announcements.title }}</h3>
        <form action="" method="POST">
            {% csrf_token %}
            {% comment %} <input type="submit" value="Confirm">
            <input type="submit" value="Cancel" onclick="window.location='{% url 'announcements:all' %}'; return false;"> {% endcomment %}
            <input type="submit" class="btn btn-primary btn-lg" value="Confirm" style="margin-right: 30px; margin-top: 30px;">
            <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{{list_all}}'; return false;" value="Cancel">
        </form>
    </div>
</div>

{% endblock %}

announcements/templates/announcements/announcements_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5" style="width: 70%;">
    <div class="col">
        <h1 class="text-center">Announcement Details</h1>
        <div class="d-flex justify-content-center">
            <table class="table table-striped mt-5" style="width: 50%">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                
                    {% for label, value in Announcements.get_fields  %}
                        <tr>
                            <td>{{label | upper}}</td>
                            <td>{{value}}</td>
                        </tr>
                    {% endfor %}
                        
                </tbody>
            </table>
        </div>

        <div class="d-flex justify-content-center">
            <a href="{% url 'announcements:all' %}" class="d-block btn btn-primary btn-lg my-5">BACK</a>
        </div>
    </div>
        
</div>

{% endblock  %}

announcements/templates/announcements/announcements_form.html
{% extends "base.html" %}

{% block content %}

<!-- BOOTSTRAP FORM -->

<div class="container d-flex justify-content-center mt-5" style="width: 25%;">
    <div class="col mt-5">
        <form action="" method="post">
            {% csrf_token %}
            <table class="table">
                {{form.as_table}}
            </table>
            <div class="container d-flex justify-content-center" style="width: 10%;">
                <input type="submit" class="btn btn-primary btn-lg" value="Submit" style="margin-right: 30px; margin-top: 30px;">
                <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{% url 'announcements:all' %}'; return false;" value="Cancel">
            </div>    
        </form> 

    </div>
</div>

<!-- END BOOTSTRAP FORM -->

{% endblock %}

announcements/templates/announcements/announcements_list.html
{% extends 'base.html' %}

{% block content %}
{% for announcements in announcements_list %}
    {% for colname in announcements.column_set.all  %}
        <p>{{colname}}</p>
    {% endfor %}
{% endfor %}


<div class="container d-flex mt-5" style="width: 70%;">
    <div class="col">
       
        <table class="table table-striped mt-5">
            <thead>
                <tr>
                    {% comment %} <th>#</th> {% endcomment %}
                    <th class="text-center" scope="col">Title</th>
                    <th class="text-center" scope="col">Description</th>
                  
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            
                {% for announcements in announcements_list %}
                <tr>
                    {% comment %} <th scope="row">{{forloop.counter}}</th> {% endcomment %}
                    <td class="ml-5"><a href="{% url 'announcements:announcements_detail' announcements.id %}">{{announcements.title}}</a></td>
                    <td class="text-center">{{announcements.year}}</td>
                    <td class="text-center">{{announcements.description}}</td>
          
                    <td><a href="{% url 'announcements:announcements_update' announcements.id %} ">Update</a></td>
                    <td><a href="{% url 'announcements:announcements_delete' announcements.id %}">Delete</a></td>
                </tr>
            {% endfor %}
        
            </tbody>
        </table>    
        <div class="d-flex justify-announcements-center">
            <a href="{% url 'announcements:announcements_create' %}" class="d-block btn btn-primary btn-lg my-5">Add New</a>
        </div>
    </div>
        
</div>

{% endblock content %}

assignments/templates/assignments/assignments_confirm_delete.html
{% extends "base.html" %}

{% block content %}

{% url 'assignments:all' as list_all %}

<div class="container d-flex justify-content-center mt-5" style="width: 50%;">
    <div class="col mt-5 text-center">
        <h1 class="mb-5">Delete content</h1>

        <p class="h5">Are you sure you want to delete the content:</p>
        <h3 class="my-5">{{ assignments.title }}</h3>
        <form action="" method="POST">
            {% csrf_token %}
            {% comment %} <input type="submit" value="Confirm">
            <input type="submit" value="Cancel" onclick="window.location='{% url 'assignments:all' %}'; return false;"> {% endcomment %}
            <input type="submit" class="btn btn-primary btn-lg" value="Confirm" style="margin-right: 30px; margin-top: 30px;">
            <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{{list_all}}'; return false;" value="Cancel">
        </form>
    </div>
</div>

{% endblock %}

assignments/templates/assignments/assignments_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5" style="width: 70%;">
    <div class="col">
        <h1 class="text-center">content Details</h1>
        <div class="d-flex justify-content-center">
            <table class="table table-striped mt-5" style="width: 50%">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                
                    {% for label, value in Assignments.get_fields  %}
                        <tr>
                            <td>{{label | upper}}</td>
                            <td>{{value}}</td>
                        </tr>
                    {% endfor %}
                        
                </tbody>
            </table>
        </div>

        <div class="d-flex justify-content-center">
            <a href="{% url 'assignments:all' %}" class="d-block btn btn-primary btn-lg my-5">BACK</a>
        </div>
    </div>
        
</div>

{% endblock  %}

assignments/templates/assignments/assignments_form.html
{% extends "base.html" %}

{% block content %}

<!-- BOOTSTRAP FORM -->

<div class="container d-flex justify-content-center mt-5" style="width: 25%;">
    <div class="col mt-5">
        <form action="" method="post">
            {% csrf_token %}
            <table class="table">
                {{form.as_table}}
            </table>
            <div class="container d-flex justify-content-center" style="width: 10%;">
                <input type="submit" class="btn btn-primary btn-lg" value="Submit" style="margin-right: 30px; margin-top: 30px;">
                <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{% url 'assignments:all' %}'; return false;" value="Cancel">
            </div>    
        </form> 

    </div>
</div>

<!-- END BOOTSTRAP FORM -->

{% endblock %}

assignments/templates/assignments/assignments_list.html
{% extends 'base.html' %}

{% block content %}
{% for assignments in assignments_list %}
    {% for colname in assignments.column_set.all  %}
        <p>{{colname}}</p>
    {% endfor %}
{% endfor %}


<div class="container d-flex mt-5" style="width: 70%;">
    <div class="col">
       
        <table class="table table-striped mt-5">
            <thead>
                <tr>
                    {% comment %} <th>#</th> {% endcomment %}
                    <th class="text-center" scope="col">Title</th>
                    <th class="text-center" scope="col">Description</th>
                  
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            
                {% for assignments in assignments_list %}
                <tr>
                    {% comment %} <th scope="row">{{forloop.counter}}</th> {% endcomment %}
                    <td class="ml-5"><a href="{% url 'assignments:assignments_detail' assignments.id %}">{{assignments.title}}</a></td>
                    <td class="text-center">{{assignments.year}}</td>
                    <td class="text-center">{{assignments.description}}</td>
          
                    <td><a href="{% url 'assignments:assignments_update' assignments.id %} ">Update</a></td>
                    <td><a href="{% url 'assignments:assignments_delete' assignments.id %}">Delete</a></td>
                </tr>
            {% endfor %}
        
            </tbody>
        </table>    
        <div class="d-flex justify-assignments-center">
            <a href="{% url 'assignments:assignments_create' %}" class="d-block btn btn-primary btn-lg my-5">Add New</a>
        </div>
    </div>
        
</div>

{% endblock content %}

content/templates/content/content_confirm_delete.html
{% extends "base.html" %}

{% block content %}

{% url 'content:all' as list_all %}

<div class="container d-flex justify-content-center mt-5" style="width: 50%;">
    <div class="col mt-5 text-center">
        <h1 class="mb-5">Delete content</h1>

        <p class="h5">Are you sure you want to delete the content:</p>
        <h3 class="my-5">{{ content.title }}</h3>
        <form action="" method="POST">
            {% csrf_token %}
            {% comment %} <input type="submit" value="Confirm">
            <input type="submit" value="Cancel" onclick="window.location='{% url 'content:all' %}'; return false;"> {% endcomment %}
            <input type="submit" class="btn btn-primary btn-lg" value="Confirm" style="margin-right: 30px; margin-top: 30px;">
            <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{{list_all}}'; return false;" value="Cancel">
        </form>
    </div>
</div>

{% endblock %}

content/templates/content/content_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5" style="width: 70%;">
    <div class="col">
        <h1 class="text-center">content Details</h1>
        <div class="d-flex justify-content-center">
            <table class="table table-striped mt-5" style="width: 50%">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                
                    {% for label, value in Content.get_fields  %}
                        <tr>
                            <td>{{label | upper}}</td>
                            <td>{{value}}</td>
                        </tr>
                    {% endfor %}
                        
                </tbody>
            </table>
        </div>

        <div class="d-flex justify-content-center">
            <a href="{% url 'content:all' %}" class="d-block btn btn-primary btn-lg my-5">BACK</a>
        </div>
    </div>
        
</div>

{% endblock  %}

content/templates/content/content_form.html
{% extends "base.html" %}

{% block content %}

<!-- BOOTSTRAP FORM -->

<div class="container d-flex justify-content-center mt-5" style="width: 25%;">
    <div class="col mt-5">
        <form action="" method="post">
            {% csrf_token %}
            <table class="table">
                {{form.as_table}}
            </table>
            <div class="container d-flex justify-content-center" style="width: 10%;">
                <input type="submit" class="btn btn-primary btn-lg" value="Submit" style="margin-right: 30px; margin-top: 30px;">
                <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{% url 'content:all' %}'; return false;" value="Cancel">
            </div>    
        </form> 

    </div>
</div>

<!-- END BOOTSTRAP FORM -->

{% endblock %}

content/templates/content/content_list.html
{% extends 'base.html' %}

{% block content %}
{% for content in content_list %}
    {% for colname in content.column_set.all  %}
        <p>{{colname}}</p>
    {% endfor %}
{% endfor %}


<div class="container d-flex mt-5" style="width: 70%;">
    <div class="col">
       
        <table class="table table-striped mt-5">
            <thead>
                <tr>
                    {% comment %} <th>#</th> {% endcomment %}
                    <th class="text-center" scope="col">Title</th>
                    <th class="text-center" scope="col">Year</th>
                    <th class="text-center" scope="col">Description</th>
                  
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            
                {% for content in content_list %}
                <tr>
                    {% comment %} <th scope="row">{{forloop.counter}}</th> {% endcomment %}
                    <td class="ml-5"><a href="{% url 'content:content_detail' content.id %}">{{content.title}}</a></td>
                    <td class="text-center">{{content.year}}</td>
                    <td class="text-center">{{content.description}}</td>
          
                    <td><a href="{% url 'content:content_update' content.id %} ">Update</a></td>
                    <td><a href="{% url 'content:content_delete' content.id %}">Delete</a></td>
                </tr>
            {% endfor %}
        
            </tbody>
        </table>    
        <div class="d-flex justify-content-center">
            <a href="{% url 'content:content_create' %}" class="d-block btn btn-primary btn-lg my-5">Add New</a>
        </div>
    </div>
        
</div>

{% endblock content %}

quizes/templates/quizes/quizes_confirm_delete.html
{% extends "base.html" %}

{% block content %}

{% url 'quizes:all' as list_all %}

<div class="container d-flex justify-content-center mt-5" style="width: 50%;">
    <div class="col mt-5 text-center">
        <h1 class="mb-5">Delete content</h1>

        <p class="h5">Are you sure you want to delete the content:</p>
        <h3 class="my-5">{{ quizes.title }}</h3>
        <form action="" method="POST">
            {% csrf_token %}
            {% comment %} <input type="submit" value="Confirm">
            <input type="submit" value="Cancel" onclick="window.location='{% url 'quizes:all' %}'; return false;"> {% endcomment %}
            <input type="submit" class="btn btn-primary btn-lg" value="Confirm" style="margin-right: 30px; margin-top: 30px;">
            <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{{list_all}}'; return false;" value="Cancel">
        </form>
    </div>
</div>

{% endblock %}

quizes/templates/quizes/quizes_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5" style="width: 70%;">
    <div class="col">
        <h1 class="text-center">Quiz Details</h1>
        <div class="d-flex justify-content-center">
            <table class="table table-striped mt-5" style="width: 50%">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                
                    {% for label, value in Quizes.get_fields  %}
                        <tr>
                            <td>{{label | upper}}</td>
                            <td>{{value}}</td>
                        </tr>
                    {% endfor %}
                        
                </tbody>
            </table>
        </div>

        <div class="d-flex justify-content-center">
            <a href="{% url 'quizes:all' %}" class="d-block btn btn-primary btn-lg my-5">BACK</a>
        </div>
    </div>
        
</div>

{% endblock  %}

quizes/templates/quizes/quizes_form.html
{% extends "base.html" %}

{% block content %}

<!-- BOOTSTRAP FORM -->

<div class="container d-flex justify-content-center mt-5" style="width: 25%;">
    <div class="col mt-5">
        <form action="" method="post">
            {% csrf_token %}
            <table class="table">
                {{form.as_table}}
            </table>
            <div class="container d-flex justify-content-center" style="width: 10%;">
                <input type="submit" class="btn btn-primary btn-lg" value="Submit" style="margin-right: 30px; margin-top: 30px;">
                <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{% url 'quizes:all' %}'; return false;" value="Cancel">
            </div>    
        </form> 

    </div>
</div>

<!-- END BOOTSTRAP FORM -->

{% endblock %}

quizes/templates/quizes/quizes_list.html
{% extends 'base.html' %}

{% block content %}
{% for quizes in quizes_list %}
    {% for colname in quizes.column_set.all  %}
        <p>{{colname}}</p>
    {% endfor %}
{% endfor %}


<div class="container d-flex mt-5" style="width: 70%;">
    <div class="col">
       
        <table class="table table-striped mt-5">
            <thead>
                <tr>
                    {% comment %} <th>#</th> {% endcomment %}
                    <th class="text-center" scope="col">Title</th>
                    <th class="text-center" scope="col">Description</th>
                  
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            
                {% for quizes in quizes_list %}
                <tr>
                    {% comment %} <th scope="row">{{forloop.counter}}</th> {% endcomment %}
                    <td class="ml-5"><a href="{% url 'quizes:quizes_detail' quizes.id %}">{{quizes.title}}</a></td>
                    <td class="text-center">{{quizes.year}}</td>
                    <td class="text-center">{{quizes.description}}</td>
          
                    <td><a href="{% url 'quizes:quizes_update' quizes.id %} ">Update</a></td>
                    <td><a href="{% url 'quizes:quizes_delete' quizes.id %}">Delete</a></td>
                </tr>
            {% endfor %}
        
            </tbody>
        </table>    
        <div class="d-flex justify-quizes-center">
            <a href="{% url 'quizes:quizes_create' %}" class="d-block btn btn-primary btn-lg my-5">Add New</a>
        </div>
    </div>
        
</div>

{% endblock content %}

templates/base.html
<!DOCTYPE HTML>
<html lang="en">

<head>

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">


{% block title %}
    {% if title %}
        <title>{{title}} | LMS</title> 
    {% else %}
        <title>LMS</title>
    {% endif %}
{% endblock title %}

{% block head %}
{% endblock head %}
    
</head>

<body>

<div class="container-fluid">
    
    <!-- NAVIGATION BAR -->


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="d-flex justify-content-around px-5 mx-auto" style="width: 80%;">
            

            <ul class="navbar-nav mt-5 mr-auto">
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'content:all' %}">Content</a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'assignments:all' %}">Assignments</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'quizes:all' %}">Quizes</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'announcements:all' %}">Announcements</a>
                </li>
                
                <!-- 
                ##
                ## UNCOMMENT THESE LINES IF YOU HAVE A FUNCTIONAL CRUD FOR THE GENRE MODEL 
                ## CHANGE ALSO THE URL INFO 'films:all' to 'films:genre_all'     
                
            

                -->

            </ul>
        </div>
    </nav>

    <!-- END OF NAVIGATION BAR -->

</div>

{% block content %}
{% endblock content %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

</body>
<style>
    li a{
       font-size: 1.6em;
       font-weight: bold; 
        color: blueviolet;
        font-family: sans-serif;
        margin: 10px;

    }
</style>
</html>